# Generated by Django 4.0.6 on 2022-07-24 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Time_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_text', models.CharField(max_length=200)),
                ('entry_passed', models.BooleanField()),
                ('time_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zeitplan.day')),
            ],
        ),
    ]
