# Generated by Django 4.0.6 on 2022-07-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeitplan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time_entry',
            old_name='time_entry',
            new_name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='day_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='day_name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='time_entry',
            name='entry_passed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='time_entry',
            name='entry_text',
            field=models.CharField(max_length=100),
        ),
    ]
