# Generated by Django 4.0.6 on 2022-07-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zeitplan', '0002_rename_time_entry_time_entry_day_day_day_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='day_name',
        ),
    ]
