# Generated by Django 4.0.6 on 2022-08-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeitplan', '0006_time_entry_entry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_entry',
            name='end_of_entry',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='time_entry',
            name='start_of_entry',
            field=models.DateField(default=None, null=True),
        ),
    ]
