# Generated by Django 4.0.6 on 2022-08-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeitplan', '0007_time_entry_end_of_entry_time_entry_start_of_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_entry',
            name='end_of_entry',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='time_entry',
            name='start_of_entry',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
