# Generated by Django 4.1.5 on 2023-02-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zeitplan", "0008_alter_time_entry_end_of_entry_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Entry_category",
            new_name="EntryCategory",
        ),
        migrations.RenameModel(
            old_name="Time_entry",
            new_name="TimeEntry",
        ),
    ]
