workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never
    - when: always

stages:
  - build
  - test

build-code-job:
  stage: build
  script:
    - echo "This is just a test."
    - python --version

test-code-job1:
  stage: test
  script:
    - echo "This is just a test."
    - python --version
